{{- if .Values.services.notificationService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: notification-service
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "dependencies.helm.sh/requires": "infrastructure-ready"
spec:
  replicas: {{ .Values.services.notificationService.replicas }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z kafka 29092; do echo waiting for kafka; sleep 2; done;']
      containers:
        - name: notification-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.services.notificationService.image.repository }}:{{ .Values.services.notificationService.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.services.notificationService.env.SPRING_KAFKA_BOOTSTRAP_SERVERS }}"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "{{ .Values.services.notificationService.env.SPRING_KAFKA_CONSUMER_GROUP_ID }}"
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "{{ .Values.services.notificationService.env.SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET }}"
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.services.notificationService.env.JAVA_TOOL_OPTIONS }}"
            - name: SPRING_MAIN_LAZY_INITIALIZATION
              value: "{{ .Values.services.notificationService.env.SPRING_MAIN_LAZY_INITIALIZATION }}"
            - name: SPRING_MAIN_BANNER_MODE
              value: "{{ .Values.services.notificationService.env.SPRING_MAIN_BANNER_MODE }}"
          resources:
            {{- toYaml .Values.services.notificationService.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: notification-service
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: notification-service
  ports:
    - port: {{ .Values.services.notificationService.service.port }}
      targetPort: 8083
  type: {{ .Values.services.notificationService.service.type }}
{{- end }}
