apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: {{ .Values.namespace }}
data:
  config.xml: |
    <clickhouse>
      <logger>
        <level>information</level>
        <console>true</console>
      </logger>
      <http_port>8123</http_port>
      <tcp_port>9000</tcp_port>
      <listen_host>0.0.0.0</listen_host>
      <max_connections>4096</max_connections>
      <keep_alive_timeout>3</keep_alive_timeout>
      <max_concurrent_queries>100</max_concurrent_queries>
      <uncompressed_cache_size>8589934592</uncompressed_cache_size>
      <mark_cache_size>5368709120</mark_cache_size>
      <path>/var/lib/clickhouse/</path>
      <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
      <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
      <users_config>users.xml</users_config>
      <default_profile>default</default_profile>
      <default_database>default</default_database>
      <timezone>UTC</timezone>
      <mlock_executable>false</mlock_executable>
    </clickhouse>
  users.xml: |
    <clickhouse>
      <users>
        <default>
          <password></password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
          <access_management>1</access_management>
        </default>
      </users>
      <profiles>
        <default>
          <max_memory_usage>10000000000</max_memory_usage>
          <use_uncompressed_cache>0</use_uncompressed_cache>
          <load_balancing>random</load_balancing>
        </default>
      </profiles>
      <quotas>
        <default>
          <interval>
            <duration>3600</duration>
            <queries>0</queries>
            <errors>0</errors>
            <result_rows>0</result_rows>
            <read_rows>0</read_rows>
            <execution_time>0</execution_time>
          </interval>
        </default>
      </quotas>
    </clickhouse>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: {{ .Values.clickhouse.image }}
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: client
        volumeMounts:
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/config.d/custom-config.xml
          subPath: config.xml
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/users.d/custom-users.xml
          subPath: users.xml
        resources:
{{ toYaml .Values.clickhouse.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: clickhouse-config
        configMap:
          name: clickhouse-config

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: client
  selector:
    app: clickhouse
  type: ClusterIP
