apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: order-processing-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseParallelGC -Djava.security.egd=file:/dev/./urandom"
            - name: SPRING_MAIN_LAZY_INITIALIZATION
              value: "true"
            - name: SPRING_MAIN_BANNER_MODE
              value: "off"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/ecommerce"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
              value: "1"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "5"
            - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              value: "20000"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "inventory-group"
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
            - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
              value: "org.apache.kafka.common.serialization.StringDeserializer"
            - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
              value: "org.springframework.kafka.support.serializer.JsonDeserializer"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES
              value: "com.pradesh.common.event"
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: "org.apache.kafka.common.serialization.StringSerializer"
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: "org.springframework.kafka.support.serializer.JsonSerializer"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: SPRING_FLYWAY_CREATE_SCHEMAS
              value: "true"
            - name: SPRING_FLYWAY_VALIDATE_ON_MIGRATE
              value: "false"
            - name: SPRING_FLYWAY_OUT_OF_ORDER
              value: "false"
            - name: SPRING_FLYWAY_CLEAN_ON_VALIDATION_ERROR
              value: "false"
            - name: SPRING_FLYWAY_BASELINE_VERSION
              value: "0"
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
            - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_READINESSSTATE_ENABLED
              value: "true"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: order-processing-system
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
