apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: order-processing-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseParallelGC -Djava.security.egd=file:/dev/./urandom"
            - name: SPRING_MAIN_LAZY_INITIALIZATION
              value: "true"
            - name: SPRING_MAIN_BANNER_MODE
              value: "off"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "notification-service-group"
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
            - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
              value: "org.apache.kafka.common.serialization.StringDeserializer"
            - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
              value: "org.springframework.kafka.support.serializer.JsonDeserializer"
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES
              value: "com.pradesh.common.event"
            - name: SPRING_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT
              value: "false"
            - name: SPRING_KAFKA_LISTENER_ACK_MODE
              value: "manual_immediate"
            - name: SPRING_KAFKA_LISTENER_CONCURRENCY
              value: "3"
            - name: SPRING_KAFKA_LISTENER_TYPE
              value: "batch"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: order-processing-system
spec:
  selector:
    app: notification-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
