server:
  port: 8084

spring:
  application:
    name: analytics-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.pradesh.common.event
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

# Kafka Topics
kafka:
  topics:
    order-created: order-created
    inventory-updated: inventory-updated
    inventory-failed: inventory-failed

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    filter: true

# Logging Configuration
logging:
  level:
    com.pradesh.analyticsservice: INFO
    org.springframework.kafka: WARN
    org.hibernate.SQL: DEBUG
