namespace: observability

clickhouse:
  image: clickhouse/clickhouse-server:23.8
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

vector:
  image: timberio/vector:0.28.1-debian
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 32Mi

grafana:
  image: grafana/grafana:9.5.2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 32Mi
  admin:
    user: admin
    password: admin
