{
 "title": "Service Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inventory Service Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, message as \"body\", raw_message as \"level\", message as \"labels\", message, pod_name, service FROM \"logs\".\"logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ( container_name = 'inventory-service' ) ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Order Service Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, message as \"body\", raw_message as \"level\", message as \"labels\", message, pod_name, service FROM \"logs\".\"logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ( container_name = 'order-service' ) ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Notification Service Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, message as \"body\", raw_message as \"level\", message as \"labels\", message, pod_name, service FROM \"logs\".\"logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ( container_name = 'notification-service' ) ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Analytics Service Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, message as \"body\", raw_message as \"level\", message as \"labels\", message, pod_name, service FROM \"logs\".\"logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ( container_name = 'analytics-service' ) ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  }
 ]
}